apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-lab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dunmer32/devops-gitops.git
    targetRevision: main
    path: charts/devops-lab
    helm:
      releaseName: lab
      values: |
        replicaCount: 2
        appVersion: "3f050ef4af16715189b5bd17832a6e3730310c4e"
        image:
          repository: "ghcr.io/dunmer32/devops-lab"
          tag: "3f050ef4af16715189b5bd17832a6e3730310c4e"
        serviceMonitor:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: lab-argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
